#!/bin/sh
#
# Copyright (c) 2012, Oracle and/or its affiliates. All rights reserved.
# 

# chkconfig: 345 90 30
# description: Oracle Unified Directory startup script


# Set the path to the Oracle Unified Directory instance to manage
INSTALL_ROOT="/home/oracle/Oracle/Middleware/asinst_1/OUD"
export INSTALL_ROOT

# Determine what action should be performed on the server
case "${1}" in
install)
  if [ "$USER" == "root" ] ; then
      echo Copying $0 to /etc/init.d
      cp $0 /etc/init.d
      echo Running chkconfig
      chkconfig --add oud
      chkconfig --list oud
  else
      echo run \"$0 install\" as root to install the rc script in /etc/init.d
      echo and set OUD to start at system boot
  fi
  ;;
start)
  /bin/su - oracle -- "${INSTALL_ROOT}/bin/start-ds" --quiet
  exit ${?}
  ;;
stop)
  /bin/su - oracle -- "${INSTALL_ROOT}/bin/stop-ds" --quiet
  exit ${?}
  ;;
restart)
  /bin/su - oracle -- "${INSTALL_ROOT}/bin/stop-ds" --restart --quiet
  exit ${?}
  ;;
*)
  echo "Usage:  $0 { start | stop | restart | install }"
  exit 1
  ;;
esac

